# Enabling H2 Console, http://localhost:8080/h2-console
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:file:~/testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

# material used
# https://blog.csdn.net/m0_37524586/article/details/88351833
# https://v.qq.com/x/page/l0891rocdcm.html
spring:
  datasource:
    url: jdbc:postgresql://localhost/springecommerece
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always

# tells spring mybatis mapper's xml(sql) located
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml