# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: ECom-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: springecommerece
    ports:
      - 5432:5432
    volumes:
      - /home/jun/Desktop/data/db/pg:/var/lib/postgresql/data # data file
      - /home/jun/Desktop/data/db/log:/var/log/postgresql # log files
      #- /mydata/mysql/data/conf:/etc/mysql/conf.d # config files
    # use docker-entrypoint-initdb.d to read sql file

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      #- "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m" # JVM memory size
    volumes:
      - /home/jun/Desktop/data/ELK/es:/usr/share/elasticsearch/data # data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - 5601:5601

  app:
    build: ..
    container_name: ECom-app
    ports:
      - 8080:8080
    depends_on:
      - db
